### ISSUE TITLE
Image updates to openjdk:8 cause build failure

### ISSUE THREAD

**Issue by yosifkit** [nuxeo/docker-nuxeo#12]
We updated the `openjdk:8` images to Debian Stretch in https://github.com/docker-library/openjdk/pull/124 so that it can follow the latest openjdk builds and have newer dependencies. As a result, libreoffice from jessie-backports fails to install. It should be new enough in Stretch to just install directly now.

Do you want me to make a PR to edit `templates/Dockerfile.ubuntu`?

**Comment by dmetzler** [comment]
Yes, Stretch offers LibreOffice 5 which is fine for us.

**Comment by dmetzler** [comment]
As I was on it (preparing for 9.2 release, I updated it), build is now green.
