### ISSUE TITLE
Install APR on Tomcat

### ISSUE THREAD

**Issue by flipovic** [nuxeo/docker-nuxeo#15]
Provide a version with Apache Tomcat Native Library (using APR on Tomcat connectors) enabled in order to optimize the server performance.

Docker official Tomcat image have this taken care of, as you can see in here:
https://github.com/docker-library/tomcat/issues/7

**Comment by dmetzler** [comment]
The recommended way of using Nuxeo is to put an Proxy in front of it which would take care of those kind of server optimization. After a quick review of what has been done on the Tomcat image, it doesn't seem it's a straightforward change (like just an `apt-get install`) and has to be validated and tested in Nuxeo itself. I've created https://jira.nuxeo.com/browse/NXP-24198 to follow that request as we don't use Github Issues for that purpose.

**Comment by flipovic** [comment]
Thank you.
