### ISSUE TITLE
Dockerfile forces the use of a specific user id on chown commands

### ISSUE THREAD

**Issue by flipovic** [nuxeo/docker-nuxeo#16]
The current Dockerfile creates the nuxeo user with a user id hard-coded (1000), which is fine, but the problem is that is forces the permissions of nuxeo installation directories with that same user id, and it doesn't provide the alternative of using the user id of the user passed via "--user" to docker run.

This leads to permissions problems when you are using a non-root user of the host to manage the image container and its volumes as they will be created with permissions associated with another user.

As a working example you can see how this was implemented on postgres official image (it requires the bind-mount of the host "/etc/passwd").

**Comment by Albenss** [comment]
I think this is always a problem...

**Comment by dmetzler** [comment]
The real requirement is that the user is part of the `root` group. We follow the guidelines of Openshift defined here: https://docs.openshift.com/container-platform/3.9/creating_images/guidelines.html#openshift-specific-guidelines
