### ISSUE TITLE
Documentation for demo setup is faulty

### ISSUE THREAD

**Issue by l-e-e-o** [nuxeo/docker-nuxeo#17]
The documentation states that a demo setup can be run with 

```
$ docker run --name mynuxeo -p 8080:8080 -e NUXEO_PACKAGES="nuxeo-web-mobile nuxeo-drive nuxeo-diff nuxeo-spreadsheet nuxeo-dam nuxeo-template-rendering nuxeo-template-rendering-samples nuxeo-showcase-content" nuxeo
```

or

```
$ docker run --name mynuxeo -p 8080:8080 -e NUXEO_PACKAGES="nuxeo-web-mobile nuxeo-drive nuxeo-diff nuxeo-spreadsheet nuxeo-dam nuxeo-template-rendering nuxeo-template-rendering-samples nuxeo-showcase-content" registry.connect.redhat.com/nuxeo/nuxeo
```

Both commands seem to include the deprecated module `nuxeo-web-mobile` and thus the container refuses to start. Could you please provide me with a valid command and fix the documentation?

**Comment by dmetzler** [comment]
Yep, this lists is definitely quite old. You can try 

`docker run --name mynuxeo --ti -p 8080:8080 -e NUXEO_PACKAGES="nuxeo-drive nuxeo-web-ui  nuxeo-showcase-content" nuxeo` which is a more reasonable list of package. 

We will update the documentation on https://github.com/docker-library/docs accordingly.

**Comment by dmetzler** [comment]
PR on documentation here https://github.com/docker-library/docs/pull/1182.

Closing the issue
