### ISSUE TITLE
Issue with docker run and env-file

### ISSUE THREAD

**Issue by othmoz** [nuxeo/docker-nuxeo#18]
Hello, I'm a beginner with both nuxeo and docker. here is how is my command:
`docker run --name mynuxeo -p 8080:8080 --restart unless-stopped  --mount source=nuxeodatavolume,target=/var/lib/nuxeo/data --env-file ./env.nuxeo.list nuxeo:latest`

env.nuxeo.list content:
```
NUXEO_PACKAGES="nuxeo-web-ui nuxeo-drive nuxeo-dam nuxeo-spreadsheet"
NUXEO_TEMPLATES="mysql"
NUXEO_DB_TYPE="mysql"
NUXEO_DB_HOST="localhost"
NUXEO_DB_NAME="nuxeo"
NUXEO_DB_USER="nuxeo"
NUXEO_DB_PASSWORD="nuxeo2018"
```

and here is my terminal feedback:

> /docker-entrypoint.sh: ignoring /docker-entrypoint-initnuxeo.d/*
> Detected Tomcat server.
> Nuxeo home:          /opt/nuxeo/server
> Nuxeo configuration: /etc/nuxeo/nuxeo.conf
> Template '"mysql"' not found with relative or absolute path (/opt/nuxeo/server/templates/"mysql"). Check your nuxeo.templates parameter, and nuxeo.template.includes for included files.
> Include template: /opt/nuxeo/server/templates/docker
> Template '"mysql"' not found with relative or absolute path (/opt/nuxeo/server/templates/"mysql"). Check your nuxeo.templates parameter, and nuxeo.template.includes for included files.
> Missing value for nuxeo.db.type, using unknown
> Malformed URL: http://127.0.0.1:null/nuxeo/runningstatus
> java.net.MalformedURLException: For input string: "null"
> 	at java.net.URL.<init>(URL.java:627)
> 	at java.net.URL.<init>(URL.java:490)
> 	at java.net.URL.<init>(URL.java:439)
> 	at org.nuxeo.launcher.monitoring.StatusServletClient.<init>(StatusServletClient.java:83)
> 	at org.nuxeo.launcher.NuxeoLauncher.init(NuxeoLauncher.java:698)
> 	at org.nuxeo.launcher.NuxeoLauncher.<init>(NuxeoLauncher.java:688)
> 	at org.nuxeo.launcher.NuxeoTomcatLauncher.<init>(NuxeoTomcatLauncher.java:41)
> 	at org.nuxeo.launcher.NuxeoLauncher.createLauncher(NuxeoLauncher.java:2411)
> 	at org.nuxeo.launcher.NuxeoLauncher.main(NuxeoLauncher.java:1101)
> Caused by: java.lang.NumberFormatException: For input string: "null"
> 	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
> 	at java.lang.Integer.parseInt(Integer.java:580)
> 	at java.lang.Integer.parseInt(Integer.java:615)
> 	at java.net.URLStreamHandler.parseURL(URLStreamHandler.java:222)
> 	at java.net.URL.<init>(URL.java:622)
> 	... 8 more
> Didn't find a known database template in the list but some template contributed a value for nuxeo.db.type.
> org.nuxeo.connect.update.PackageException: Package not found: "nuxeo-web-ui

I would like nuxeo to use the mysql instance created at the host 
Any help is appreciated

**Comment by othmoz** [comment]
I had a problem with the env-file, I removed the quotation marks and it worked.
also for mysql I removed localhost and put the host's actual IP

**Comment by dmetzler** [comment]
Closing the issue as you found the solution.

`localhost` can't work as Nuxeo is running in a container. If you run MySQL and Nuxeo in the same docker-compose file, you could use the DNS address of the MySQL container.
