### ISSUE TITLE
L'intégration de ffmpeg à l'image nuxeo officielle ne fonctionne pas

### ISSUE THREAD

**Issue by fx-leb** [nuxeo/docker-nuxeo#2]
Bonjour,

Le docker file proposé (cf. https://hub.docker.com/r/library/nuxeo §ffmpeg) pour l'intégration de ffmpeg à l'image officielle ne fonctionne pas sur mon poste.
J'ai du ajouter les paquets git et sudo pour réussir à builder l'image : 

```
RUN apt-get update && apt-get install -y --no-install-recommends libfaac-dev git sudo
```

**Comment by dmetzler** [comment]
Thx for the feedeback, a PR is done on official doc : 

https://github.com/docker-library/docs/pull/462
