### ISSUE TITLE
Unable to log in using Administrator/Administrator

### ISSUE THREAD

**Issue by davidballester** [nuxeo/docker-nuxeo#35]
Hello. I've just deployed a Nuxeo container using this command:

```
docker run --name mynuxeo -d -p 8080:8080 nuxeo
```

Then, I added the UI addon by bashing into the container and running:

```
nuxeoctl mp-install nuxeo-web-ui-2.4.0
```

Now, I can access the login page of the UI, but when I input the default credentials, user: `Administrator`, password: `Administrator`, I don't get an `Invalid username or password`, as I do when I input other credentials, but I get redirected to the login page again without any feedback.

In the inspector, I can see a request to `/ui` returning a `401`

![401](https://user-images.githubusercontent.com/1730892/64323257-6b2a8880-cfc4-11e9-850f-6ecd4ce4178b.PNG)

I'm using [Docker Toolbox](https://docs.docker.com/toolbox/), in case it's an issue with the host being the IP of the virtual machine instead of localhost.

What's the problem?

**Comment by dmetzler** [comment]
Hello, you may find documentation on how to use Docker with Nuxeo here:  https://doc.nuxeo.com/nxdoc/setting-up-your-nuxeo-environment/ and here: https://doc.nuxeo.com/corg/docker-usage/ 

You can also follow the courses on Nuxeo University: https://university.nuxeo.com

I'm closing the issue as it is not a problem with Docker packaging but more about usage. 
To get support, you can also call our sales representatives.
