### ISSUE TITLE
pre installed hotfixes

### ISSUE THREAD

**Issue by fantapop** [nuxeo/docker-nuxeo#36]
Hi, can the docker images be updated to include preinstalled hotfixes?  If not, is there a way I can install them at container build time from my own dockerfile?

**Comment by dmetzler** [comment]
The public image doesn't include hotfixes because it's part of what is offered with the Nuxeo subscription. 
You can install them by building your own image using regular `nuxeoctl` command: https://doc.nuxeo.com/nxdoc/nuxeoctl-and-control-panel-usage/
