### ISSUE TITLE
Request for 2021-LTS

### ISSUE THREAD

**Issue by yardenshoham** [nuxeo/docker-nuxeo#45]

**Comment by tomasdelvechio** [comment]
I found in the Nuxeo Doc a private registry for build images from 2021-LTS [1]. Perhaps this repo is no longer update?

[1]: https://doc.nuxeo.com/nxdoc/build-a-custom-docker-image/

**Comment by ataillefer** [comment]
Hi @tomasdelvechio, indeed, this repository is no longer maintained.

The source code of Nuxeo LTS 2021 is now in a private repository, thus the private registry for the Docker image...

Yet, there is an open source version of the Nuxeo Docker image:
- Source code [repository](https://github.com/nuxeo/nuxeo/tree/master/docker).
- Docker image [registry](https://packages.nuxeo.com/#browse/search/docker=attributes.docker.imageName%3Dnuxeo%2Fnuxeo). You can use the `latest` tag for the latest release (currently 11.4) and the `11.x` tag for the latest build (currently 11.5.129).

Hope this helps.

**Comment by yardenshoham** [comment]
Please add this information to Docker hub. Currently, the impression is that the official Docker image is being maintained.
https://hub.docker.com/_/nuxeo
