### ISSUE TITLE
can't start a nuxeo container

### ISSUE THREAD

**Issue by fx-leb** [nuxeo/docker-nuxeo#5]
When I start a nuxeo:7.10 container, this errors occurs : 

> Could not run configuration: Nuxeo requires Java 1.8.0_40+ (detected 1.8.0_102). See 'jvmcheck' option to bypass version check.

I use this simple command :

> docker run -d --name nuxeo -p 8082:8080  nuxeo:7.10

It seems related to https://jira.nuxeo.com/browse/NXP-20189

**Comment by jiririedl** [comment]
hotfix: just add -e LAUNCHER_DEBUG="-Djvmcheck=nofail"

**Comment by fx-leb** [comment]
Thanks, it works.
